# DynamoDB calculator - https://zaccharles.github.io/dynamodb-calculator/
#  

services:

  dynamodb:
    image: amazon/dynamodb-local:2.4.0
    command: "-jar DynamoDBLocal.jar -sharedDb"
    healthcheck:
      test: [ "CMD-SHELL", "curl -v http://dynamodb:8000" ]
      interval: 3s
      timeout: 3s
      retries: 5
      start_period: 3s
    ports:
      - "8000:8000"
    restart: always

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:4.6.1
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb:8000"
      AWS_REGION: "eu-west-2"
      AWS_ACCESS_KEY_ID: abc
      AWS_SECRET_ACCESS_KEY: xyz
    depends_on:
      dynamodb:
        condition: service_healthy

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - D:\DockerCompose\dynamoDB\mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=plusinfosys
  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient_container
    ports:
      - "8003:3000"

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - D:\DockerCompose\dynamoDB\redis:/data
    command: redis-server --appendonly yes    
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight_container
    ports:
      - "8002:5540" 
