services:
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: llama-cpp-cpu
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - D:\DockerCompose\llama.cpp\models:/models
    # Hint: Replace '--threads 8' with your actual CPU physical core count
    command: >            
      -m /models/qwen2.5-coder-3b-instruct-q8_0.gguf
      -c 4096
      --threads 8
      --host 0.0.0.0
      --port 8086
      --chat-template chatml      
#-m /models/Qwen3.5-2B-UD-Q8_K_XL.gguf
#-m /models/codellama-13b.Q5_K_M.gguf
